#!C:\Users\Sahiba\OneDrive\Documents\GPCSSI project\CLone\DARC\darc_venv\Scripts\python.exe
# Copyright 2014-2017, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import stem.interpreter

if __name__ == '__main__':
  stem.interpreter.main()
